const funfacts = [
  'Banging your head against a wall for one hour burns 150 calories.',
  'In Switzerland it is illegal to own just one guinea pig. This is because guinea pigs are social animals, and they are considered victims of abuse if they are alone. Why isn’t this a law everywhere?!',
  'Pteronophobia is the fear of being tickled by feathers.',
  'Snakes can help predict earthquakes.',
  'Crows can hold grudges against specific individual people.',
  "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
  "Cherophobia is the word for the irrational fear of being happy.",
  "Nearly 30,000 rubber ducks were lost a sea in 1992 and are still being discovered today.",
  "It's Impossible to Hum While You Hold Your Nose",
  'The oldest “your mom” joke was discovered on a 3,500 year old Babylonian tablet.',
  "The inventor of the frisbee was turned into a frisbee after he died.",
  'Instead of saying "cheese" before taking a picture, Victorians said "prunes."',
  'McDonald’s once made bubblegum-flavored broccoli.',
  'The first oranges weren’t orange.',
  'The Barbie doll’s full name is Barbara Millicent Roberts.',
  'Three presidents, all Founding Fathers—John Adams, Thomas Jefferson, and James Monroe—died on July 4.',
  'The tallest man ever recorded was American giant Robert Wadlow, who stood 8 feet 11 inches.',
  'The tallest living man is 37-year-old Sultan Kosen, from Turkey, who is 8 feet, 2.8 inches.',
  'Did you know that if you subscribe to TheWaildug on YouTube you will become god.',
  'Experiments in universities have actually been carried out to figure out how many licks it takes to get to the center of a Tootsie Pop, both with machine and human lickers. The results ranged from 252 to 411.',
  'The Four Corners is the only spot in the US where you can stand in four states at once: Utah, Colorado, Arizona and New Mexico. ',
  'Canada is south of Detroit (just look at a map).',
  '29th May is officially “Put a Pillow on Your Fridge Day”.',
  '7% of American adults believe that chocolate milk comes from brown cows.',
  'Most Korean people don’t have armpit odor.',
  'During your lifetime, you will produce enough saliva to fill two swimming pools. Gross 🤮',
  'If Pinocchio says “My Nose Will Grow Now”, it would cause a paradox.',
  'Movie trailers were originally shown after the movie, which is why they were called “trailers”.',
  'The smallest bone in your body is in your ear.',
  'Tennis players are not allowed to swear when they are playing in Wimbledon. Because of this, line judges have to learn curse words in every language so they know when a player has violated the rules.',
  'The top six foods that make your fart are beans, corn, bell peppers, cauliflower, cabbage and milk. I wish I never did this fact.',
  'The longest English word is 189,819 letters long.',
  'A day in Mercury lasts approximately long as 59 days on Earth.',
  'No number before 1,000 contains the letter A.'
]
module.exports = funfacts